### ISSUE TITLE
Fails to load - Unexpected token 'export'

### ISSUE THREAD

**Issue by AnnieTheEagle** [OMGDuke/protondb-decky#84]
Currently, the latest version does not work with the latest stable Decky Loader.

The error is:
```
Unexpected token 'export'
  at PluginLoader.importReactPlugin(http://localhost:1337/frontend/chunk-00b6e60c.js:6984:48)
  at async PluginLoader.importPlugin(http://localhost:1337/frontend/chunk-00b6e60c.js:6959:17)
```

Decky Loader: 2.12.3
Proton Badges: 1.1.0-dbec43e
Steam OS: 3.5.19

**Comment by OMGDuke** [comment]
Only works on the pre release version of decky
